stages:
  - build

android-build-release:
  stage: build
  image: paritytech/parity-signer
  tags:
    linux-docker
  only:
    - master
    - /^[0-9]+$/
    - mp-gitlab-build
  script: |
    cat "$KEYSTORE_DATA" | base64 -d > /tmp/gitlab-ci.keystore
    /build/scripts/build-release.sh /tmp/gitlab-ci.keystore "$KEYSTORE_ALIAS" "$KEYSTORE_PASS"
