[package]
name = "transaction_signing"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
ethsign = { version = "0.7.3", default-features = false, features = ["pure-rust"] }
sp-core = "3.0.0"
serde_json = "1.0"
hex = "0.4.3"
lazy_static = "1.4.0"
db_handling = {path = "../db_handling"}
sled = "0.34.6"
parity-scale-codec = "2.1.1"
